const NPM_ORG_MEMBER = 'developer';
const NPM_ORG_ADMIN = 'admin';
const NPM_ORG_OWNER = 'owner';

const NPM_2FA_NONE = 'disabled';
const NPM_2FA_AUTH_ONLY = 'auth-only';
const NPM_2FA_AUTH_AND_WRITES = 'auth-and-writes';

const GITHUB_COLLABORATOR_ADMIN = 'admin';
const GITHUB_COLLABORATOR_WRITE = 'write';
const GITHUB_COLLABORATOR_READ = 'read';
const GITHUB_COLLABORATOR_NONE = 'none';

const GITHUB_COMMIT_STATUS_PENDING = 'pending';
const GITHUB_COMMIT_STATUS_SUCCESS = 'success';
const GITHUB_COMMIT_STATUS_ERROR = 'error';

const GITHUB_PUBLISH_CONTEXT = 'Publish';

module.exports = {
  NPM_ORG_MEMBER,
  NPM_ORG_ADMIN,
  NPM_ORG_OWNER,
  NPM_2FA_NONE,
  NPM_2FA_AUTH_ONLY,
  NPM_2FA_AUTH_AND_WRITES,
  GITHUB_COLLABORATOR_ADMIN,
  GITHUB_COLLABORATOR_WRITE,
  GITHUB_COLLABORATOR_READ,
  GITHUB_COLLABORATOR_NONE,
  GITHUB_COMMIT_STATUS_PENDING,
  GITHUB_COMMIT_STATUS_SUCCESS,
  GITHUB_COMMIT_STATUS_ERROR,
  GITHUB_PUBLISH_CONTEXT
};
